apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: mysqlnamespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mysqlvolume       # path on the host machine (here minikube)