apiVersion: v1
kind: Service
metadata:
  name: hello-world-api-service    # Specifies the name of the service, making it identifiable
  namespace: mynamespace
spec:
  selector:
    app: hello-world-api          # Selects pods based on the specified label (app: hello-world-api)
  ports:
    - protocol: TCP
      port: 81                    # Exposes port 81 on the service
      targetPort: 8080            # Assuming your Spring Boot app is running on port 8080
  type: NodePort